### ISSUE TITLE
Sample images are not generated during training

### ISSUE THREAD

**Issue by harrywang** [d8ahazard/sd_dreambooth_extension#1026]
I am kind of confused about the difference between Sanity Sample Prompt and Sample Image Prompt:
<img width="779" alt="Screenshot 2023-03-06 at 2 46 01 PM" src="https://user-images.githubusercontent.com/595772/223215551-cfe23c3a-da1a-4afe-a4d8-01891b51f69b.png">
<img width="790" alt="Screenshot 2023-03-06 at 2 46 12 PM" src="https://user-images.githubusercontent.com/595772/223215564-91acbc1d-d749-4554-afca-554b71255ab3.png">

During training, the Sanity Sample Prompt result seems to show but I thought the Sample Image prompt is used to show how each checkpoint is doing in terms of training effect, correct? Also, I don't know what the first image shown below during training.
<img width="851" alt="Screenshot 2023-03-06 at 2 47 12 PM" src="https://user-images.githubusercontent.com/595772/223215574-16845fff-4f69-4773-9fe2-4809160e1c1f.png">

The log shows the samples are not generated and I don't see generated beckham during training as well. 
```
Generating Samples:   0% 0/4 [00:00<?, ?it/s, inst_loss=0, loss=0.00511, lr=0.0002, prior_loss=0.00681, vram=8.7]
Generating Samples:   0%  0/4 [00:00<?, ?it/s, inst_loss=0, loss=0.0062, lr=0.0002, prior_loss=0.00827, vram=8.7]
```

I hope I explained the issue clearly - thanks!

**Comment by Arilziem** [comment]
Sample prompts are per concept, sanity prompt is for the whole thing. The idea is that you check if your concept (in this case "david-beckham") is being adopted in the `sample prompt`, and that your overall model is not suffering from overfitting/overspill in the `sanity prompt`. So you can put something unrelated into the sanity prompt and abort training it changes too much compared to the untrained model.

From the screenshot I can tell that the samples are in fact being generated, the left-most image will be the sanity sample, then your concept sample, and then two plots that are also counted as samples. Your sanity sample does not look very _sane_, but that is likely because the model does not understand what "ohwx" is. Your sample not looking like your subject will be related to your training settings and possibly the images your are using.

I would suggest you post in `Discussion` (or another stable diffusion community) if you need help finding the right training approach.

**Comment by harrywang** [comment]
> Sample prompts are per concept, sanity prompt is for the whole thing. The idea is that you check if your concept (in this case "david-beckham") is being adopted in the `sample prompt`, and that your overall model is not suffering from overfitting/overspill in the `sanity prompt`. So you can put something unrelated into the sanity prompt and abort training if it changes too much compared to the untrained model.
> 
> From the screenshot I can tell that the samples are in fact being generated, the left-most image will be the sanity sample, then your concept sample, and then two plots that are also counted as samples. Your sanity sample does not look very _sane_, but that is likely because the model does not understand what "ohwx" is. Your sample not looking like your subject will be related to your training settings and possibly the images your are using.
> 
> I would suggest you post in `Discussion` (or a stable diffusion community) if you need help finding the right training approach.

Thanks for the reply - very useful. I am closing this for now.
