### ISSUE TITLE
High memory consumption when saving snapshots

### ISSUE THREAD

**Issue by Arilziem** [d8ahazard/sd_dreambooth_extension#1072]
There have been a lot of issues lately with users running out of memory (system RAM), see e.g. #1000 #1055 #1062 #1065

The common theme is having "Save snapshots" / `save_state_*` enabled, ~which I believe is the default at the moment (?).~

I am not sure how this should be addressed though. ~It could be disabled by default, and~ a hint about the increased RAM usage could be added. But maybe there is also a way to reduce the amount of RAM that is needed for this step.

Lastly, it might be beneficial to also track system RAM in addition to VRAM, so that users can be made aware of low system memory (or it at least might show up in the logs, making it easier to debug).

**Comment by ArrowM** [comment]
All of the Snapshot options are disabled by default.

**Comment by ArrowM** [comment]
Can you please update to the latest version of the extension and let me know if that helps at all?

**Comment by Arilziem** [comment]
I probably won't be able to see any issues since I have a tiny 10GB GPU but 64GB system RAM. @minienglish1 maybe?

**Comment by d8ahazard** [comment]
> I probably won't be able to see any issues since I have a tiny 10GB GPU but 64GB system RAM. @minienglish1 maybe?

Out of pure curiosity - how are you creating issues without using the templates?

As you're a regular contributor and a name I recognize, I think we've been granting a bit of leeway on our "Close the issues if it's not using the template" policy, but it still begs the question...are you just deleting the template and posting, or are you using a specific URL or something that just drops you in a blank form?

I'm asking purely because there have been plenty of times where people post "non-template" issues, and it drives me nuts that I can't figure out how. And, of course, the most obvious answer is often the correct one. 

In regards to your issue...I think tracking the used system RAM might be beneficial. I/we'll keep that one in mind for future updates.

Actually saving the snapshots or doing anything about RAM usage is a tricky one. I'm guessing the application is dumping the contents of VRAM to memory, then saving it to HDD...but I'd have no idea how to fix it. My guess is an issue might need to be raised in the Accelerator repo for that bit, as I'm just using their native method.

Or, we could rip the code apart and hack our own version that works better. We'll see how much time is allowed. 

Either way, we may want to mark this one as an "Enhancement" and rename it, for reasons explained above.

**Comment by minienglish1** [comment]
It's on my list to test if a system ram OOM error is the cause of snapshots causing the model not to train (wouldn't a larger page file fix that though?).  That along with why [1, 4] aspect ratio caused my [1, 4] bucket to jump from 3 images on main to 22 image on dev.  It's the weekend again, so I'm busy managing my school.  Maybe Tuesday/Wednesday I can take a look at them.

**Comment by ArrowM** [comment]
I'm pretty sure we could add a bot if we wanted the template to be strictly enforced

**Comment by minienglish1** [comment]
> I'm pretty sure we could add a bot if we wanted the template to be strictly enforced

I think this is your best option.  1st line of the form stating: If you don't use this form, your issue will be immediately deleted.  

You freely give away your time to build this.  If people won't respect that by filling out a form, you shouldn't waste more of your time on them.  Got to respect yourself.  I routinely fire employees, students, and parents for not following the rules.  Don't even think twice about it anymore.  My school is so much better for it.

**Comment by Arilziem** [comment]
This taking a weird turn. 99% of the time the template thing is not about respect but about people having limited (mostly mental) resources - stress, no technical background, no time, ...

Not really interested in this type of interaction or the direction this is going, so I'm closing this.
