### ISSUE TITLE
Dreambooth still uses Diffusers 16.1 instead of latest 18.2

### ISSUE THREAD

**Issue by mrvirus9898** [d8ahazard/sd_dreambooth_extension#1309]
### Kindly read the entire form below and fill it out with the requested information.

Dreambooth's requirements.txt specifies diffusers 16.1, but the latest python diffusers is 18.2. New extensions for Auto1111 require 18.2, instead of requiring users to override the requirements of Dreambooth, it would be great if Dreambooth went up to diffusers 18.2 to future proof against install clashes as technology progresses.  

requirements.txt line 4
diffusers~=0.16.1 -> diffusers~=0.18.2

I updated my local copy to 18.2 and so far no issues. I am willing to go through a QA processes to see if Dreambooth as any issues with 18.2 (it really should not but just in case). Do you have any test cases you would like me to try?

**Comment by Yuyuyang** [comment]
I updated my Auto1111 Webui to v1.5.0 and Dreambooth's tab disappears. Maybe the version of diffusers leads to this problem cause v1.5.0 supports SD XL and SD XL requires diffusers >= 0.18.0

**Comment by DaveScream** [comment]
I think that there is different approach. A1111 should be on edge with updates because of new features, scripts, addons.

On the other side dreambooth should be very conservative with updates because in finetuning any change can be hard to detect, too many options.

Maybe developers should have some test datasets to look how learning process differs from version to version, and when some settings change.
