### ISSUE TITLE
Whether "aspect-atio-bucketing" can be used

### ISSUE THREAD

**Issue by mutucc** [d8ahazard/sd_dreambooth_extension#176]
Project address:https://github.com/NovelAI/novelai-aspect-ratio-bucketing
Use "Aspect atio bucketing" to train without cutting pictures and improve the output quality. Whether it can be used in the dreambooth

**Comment by d8ahazard** [comment]
Not necessarily impossible, but would definitely require some retrofitting on the part of the main script.

First, it looks like we'd need to generate a .pkl file of all the existing images, and/or adjust the main aspect-ratio-bucketing script to utilize arrays instead of a .pkl file, then adjust the main dreambooth training script to use the generated buckets to run multiple epochs based on each set of found aspect ratios.

So, definitely not a "no", but I've got a lot on my plate, so IDK when I could get to working on this.

**Comment by sgsdxzy** [comment]
I'd love this, but would rather wait for it to land in webui's traning system first.

**Comment by d8ahazard** [comment]
> I'd love this, but would rather wait for it to land in webui's traning system first, and hopefully we can reuse the preprocessing part.

I don't think it necessarily has to go in the training/preprocessing system tho. That'd only be if we force people to create a .pkl file just to train dreambooth. I suspect that it might be fairly trivial to force the script to just use an input array of images, and create the "buckets" with that, which looks to be just a list of image indices within the pkl file that share the same "magick" dimensions. If we just use the image index in the overall "dreamboothdataset" array and tell the class to use the DBDataset instead of a .pkl, I bet we could do the same thing.

**Comment by sgsdxzy** [comment]
There are some training scripts:
https://github.com/bmaltais/kohya_ss/blob/master/diffusers_fine_tuning/fine_tune.py
https://github.com/harubaru/waifu-diffusion/blob/main/trainer/diffusers_trainer.py

Don't know how much we can learn from them.

**Comment by d8ahazard** [comment]
> There are some training scripts: https://github.com/bmaltais/kohya_ss/blob/master/diffusers_fine_tuning/fine_tune.py https://github.com/harubaru/waifu-diffusion/blob/main/trainer/diffusers_trainer.py
> 
> Don't know how much we can learn from them.

Honestly, in looking at this, it seems like it's basically just implementing those three classes, figuring out how we pass multiple concepts to it, and then replacing our current sampler with the one shown here. This is from the waifu repo.

![image](https://user-images.githubusercontent.com/1633844/202336121-4d77ec31-d536-4ad5-9e52-2937b9f688d5.png)

**Comment by sgsdxzy** [comment]
@d8ahazard I think there are two ways to do this:

1. Add a preprocess step, sort images to different directories/add metadata to them, and load the sorted directory.
2. Load the old dataset and bucket them on the fly (WD doies this).

I would choose the first one, as it is easier to verify the bucketing results, and you only need to process the same dataset once, and probably one day the new dataset could be used by TI/HN training. However the preprocessing step is not a part of dreambooth and probably should go to a standalone extension/script?

**Comment by d8ahazard** [comment]
So, an update to this:

I haven't implemented bucketing...yet...but I've started working on a new Dataset class that should allow us to deal with multiple "sets" of images more intelligently.

Presently, I'm working on just being able to stop training a specific concept at a specific number of steps and keep training others, but this mechanism should ultimately be extensible to iterating through "buckets" of images at a time, versus round-robin with a group of concepts. :)

**Comment by CodeExplode** [comment]
If you're using a batch size of 1 due to low vram, you don't actually need to bucket and can just resize images to image sizes which SD accepts (64 pixel width/height intervals). I've rewritten things a bit to use a custom 4.1k tagged data source, but on each image data item thing I also have a target size for it to be resized to, and find the closest valid target size for the aspect ratio ike this:

resolutions = [ [512, 512], [576,512],[512,576], [640,512],[512,640], [704,512],[512,704], [768,512],[512,768], [832,512],[512,832]]

# inspired by https://github.com/victorchall/EveryDream-trainer/blob/main/ldm/data/data_loader.py#L72
aspect = w/h
self.target_size = resolutions[0]
for resolution in resolutions:
     if abs(resolution[0]/resolution[1] - aspect) < abs(self.target_size[0]/self.target_size[1] - aspect):
               self.target_size = resolution
               
In my case I've already selected regions in the image of valid aspect ratios using [another tool](https://github.com/CodeExplode/Image-Tagger/) I made (the aspect ratio selections code isn't up on github yet since it needs some cleanup from a lot of changes).

**Comment by d8ahazard** [comment]
Implemented!
