### ISSUE TITLE
Option to train textual inversion embeddings instead of text encoder

### ISSUE THREAD

**Issue by elias-sundqvist** [d8ahazard/sd_dreambooth_extension#199]
**Option to train textual inversion embeddings instead of text encoder**

> disclaimer: This is just an idea I have. I don't know how well it will work in practice. 

The idea is that you provide a list of tokens that should be replaced with TI embeddings. (Such as the names of specific people you want to train on. ).  These embeddings could either be randomly initialized, initialized to match some word like "Person", or copied from an existing embedding file. Instead of training the text encoder, you only update the embeddings for the specified tokens. 

**Example**

Specified embedding tokens: `Alice, Bob`

File names: `A photo of Alice.png, A photo of Bob.png`

Prompts:  `A photo of <alice-embedding>,  A photo of <bob-embedding>`

**Motivations**

This should have similar benefits to the technique of random naming in https://github.com/TheLastBen/fast-stable-diffusion (reduced need for regularization images), but the tokens would be human readable and easy to remember instead of random gibberish. 

Another benefit is that the learned embeddings could be used with other models than the one you are currently training. This could potentially let you 1. use the concept in a new model without any extra training 2. fine-tune the concept into a new model more quickly.

**Comment by sgsdxzy** [comment]
May I ask what's the difference between this and standard TI?

**Comment by elias-sundqvist** [comment]
> May I ask what's the difference between this and standard TI?

You still train the (unet) model weights here. So with the trained model the results should be the same quality as normal dreambooth. 

You can use the learned embeddings with other models as well, but in this case the results will not be as good (probably similar to normal TI).

**Comment by d8ahazard** [comment]
As I understand it now, I don't think this is something I'm going to implement here. TI feels like "It's own thing", and trying to utilize it here just seems like muddying up the waters. 

Someone wants to argue with me and convince me why I should change my mind, go for it. I'm always open to a good discussion.

But for now, for the sake of trying to figure out which issues are actual issues, I'm going to close this.

**Comment by elias-sundqvist** [comment]
Ok, no worries :)
I might consider implementing this myself in the future. Not sure if I will have the time though.
Would you be interested in a PR in that case, or should I make a separate extension?

**Comment by d8ahazard** [comment]
If it's optional, I'm happy to merge any pr that further helps to enhance the project. There are just some things I don't have enough time for in a day. Lol.

**Comment by CodeExplode** [comment]
I just had this same idea and think the potential might be underestimated. If you're trying to train say a bunch of artists who names are like FireRose1 and KingOfDemons etc, these are going to get interpreted as regular words and start impacting those. However if you have a simple embedding manager layer which catches the known prompt words like the current method does by matching to embedding filenames, you could insert that embedding in the prompt instead of the CLIP embedding, and then train just that one embedding vector instead of the whole text model. Essentially 'ArtLord101' would never be associated with the words art or lord or 101, and could be associated with an initialization prompt used to make the embedding (e.g. 'greg rutkowski').

**Comment by CodeExplode** [comment]
Expanding on the above, from what I can tell the process is all covered in this class which wraps the text encoder: https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/modules/sd_hijack.py#L120

It handles the web UI prompt weighting, but also can look up embeddings from the embedding database (which is just the list of embedding files, which were created in the train tab by by getting an embedding tensor(s) from the clip model for some given prompt text which initializes the embedding, i.e. with no training it will behave exactly the same as that prompt text).

It reads the prompt and checks if any words match the embedding filenames (line 166), in which case it reserves a certain number of positions to be filled with the embedding vectors (line 182). e.g. An embedding might be 4 vectors long if it was initialized with the text 'man with red hat', and some words also don't exist in the CLIP text encoder, like 'computer' which gets turned into 2 words, 'compu' and 'ter' which are used sequentially and so use 2 vector spaces in the prompt. A single word which matches a filename of an embedding with 2 vectors does the same thing.

That's all called from the forward function when requesting the embedding vectors for a given text string, and returns the array of embedding vectors which is a mixture of the CLIP results and the embedding file pre-saved embeddings. At line 355 I think the rest of the text encoder model is applied to the embeddings, which mixes them with positional embeddings (some fancy black magic to indicate where the embedding vector is in the prompt for SD to understand, I think, which is how it understands words which go together in sequence like 'compu' and 'ter', or 'blonde woman').

There's also code there for stopping at the nth layer of the text encoder, which means we could train like Novel AI did which apparently led to much better results somehow (ignoring the final stages of the CLIP model).

Presumably the embedding vector would need to be unfrozen and included in the torch parameters. It might be that it should be frozen/unfrozen depending on whether it was used in a given prompt, or that batches would need to be built so that the same embeddings are active for training in each of them, similar to Novel AI's aspect ratio bucketing, but I'm not sure if that's necessary or if you can just set the embedding to unfrozen and start training regardless of whether it appears in a prompt.
