### ISSUE TITLE
Dreambooth Tab is missing after last update 

### ISSUE THREAD

**Issue by pandasonic-collective** [d8ahazard/sd_dreambooth_extension#215]
**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
yes
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
yes
**Have you updated Dreambooth to the latest revision?**
yes
**Have you updated the Stable-Diffusion-WebUI to the latest version?**
yes
**Please find the following lines in the console (After "Installing Requirements for WebUI") and paste them below. If you don't see these lines in the console, then update Dreambooth**
I still have never seen this displayed or printed anywhere in the console. 

`Dreambooth revision is *****************************************
Diffusers version is ********.
Torch version is *********.
Torch vision version is ********.`

**Describe the bug**
(A clear and concise description of what the bug is)
Dreambooth Tab in Stable Diffusion is missing

**Provide logs**
If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

Warning: k_diffusion not found at path S:\Stable Diffusion\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py
Preloading Dreambooth!
[!] Not using xformers memory efficient attention.
[!] Not using xformers memory efficient attention.
Dreambooth API layer loaded
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Loading weights [8dce9547] from S:\Stable Diffusion\stable-diffusion-webui\models\Stable-diffusion\br33zytest2_1200.ckpt
Applying cross attention optimization (Doggettx).
Model loaded.
Loaded a total of 0 textual inversion embeddings.
Embeddings:
Error executing callback ui_tabs_callback for S:\Stable Diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\main.py
Traceback (most recent call last):
  File "S:\Stable Diffusion\stable-diffusion-webui\modules\script_callbacks.py", line 93, in ui_tabs_callback
    res += c.callback() or []
  File "S:\Stable Diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\main.py", line 164, in on_ui_tabs
    db_performance_wizard.click(
TypeError: Clickable.click() missing 1 required positional argument: 'inputs'

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

**Environment**
What OS? Win11
If Windows - WSL or native? native
What GPU are you using? 3090 ti

**Comment by pandasonic-collective** [comment]
I just pulled the latest update and it is back

**Comment by d8ahazard** [comment]
So, the reason I harp so much about the template is largely due to this line here:

Please find the following lines in the console (After "Installing Requirements for WebUI") and paste them below. If you don't see these lines in the console, then update Dreambooth
I still have never seen this displayed or printed anywhere in the console.

Dreambooth revision is ***************************************** Diffusers version is ********. Torch version is *********. Torch vision version is ********.


Which I request people fill out from their console so I know what versions of things they're running.

In your case, I'm going to hazard a guess and say you have an old gradio version installed, which is getting mad because this argument isn't there.

As you just discovered, I still fixed this, but you'll probably run into problems somewhere else until you update your version of the SD-WebUI base.
