### ISSUE TITLE
UI "Don't Cache Latents" description text mismatch from README

### ISSUE THREAD

**Issue by ulysse-gen** [d8ahazard/sd_dreambooth_extension#224]
```
Python 3.9.15 (main, Oct 12 2022, 19:14:24) 
[GCC 9.4.0]
Commit hash: 98947d173e3f1667eba29c904f681047dea9de90
Installing requirements for Web UI
loading Dreambooth reqs from /notebooks/stable-diffusion-webui/extensions/sd_smartprocess/requirements.txt
Checking Smart Crop requirements.


Installing requirements for Dreambooth
Checking Dreambooth requirements.
Dreambooth revision is 59f93b3bf5b8540d3ecbae96133099f2e6ad180e
Diffusers version is 0.7.2.
Torch version is 1.12.0+cu116.
Torch vision version is 0.13.0+cu116.
```

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes I did sir

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes I did sir

**Have you updated Dreambooth to the latest revision?**
No sir, but it's unchanged.

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes, I did sir.

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**
erm.. ok.. kind of.. no I did not cuz its currently training, but I looked thru "dreambooth.js" on the last commit and saw it was not changed.

**Describe the bug**
The description for "Don't Cache Latents" says one thing on the README and seems to say the opposite on the UI.
It might be just me misunderstanding this, but it seems like on the UI it says "Uncheck to save VRAM" while on the README it says "Enable to save VRAM", but enable can be seen as checking the checkbox.

**Screenshots/Config**
![image](https://user-images.githubusercontent.com/75956530/202075632-ee2bf9e4-5155-4ab5-8ea7-f37a55d49ae9.png)
![image](https://user-images.githubusercontent.com/75956530/202075739-2c4cbeca-2a9a-49ab-bd70-2a2b6befabb8.png)

**Comment by Slowly-Grokking** [comment]
I think the english all checks out. In this context 'enabling is referring to the checkbox and not the state of caching.  It just seems weird because you're enabling a negative - "don't cache." 

Unckecked: Caches the latents and uses more ram, and is a little faster. (caching enabled)
Checked: Does not cache, uses less ram, and is a little slower.  (caching disabled)

It would be more straight forward to have the checkbox state match the state of [latent caching], but it is described accurately as it is.

**Comment by d8ahazard** [comment]
> Yea that is what i thought too, just felt like id still make a report about it because it might get people confused.

You're right, it's weird that it's not just "Cache Latents" instead of a checkbox to enable a negative. 

Reasoning for it is simply because that's what the source "train_dreambooth" script(s) call it, and I'm trying to make it as easy as possible to update the base scripts to work with this extension whenever updates are issued. If I change the variable name, then I either need to add some extra logic between the UI and the training script to flip the value, or rename variables in the base script, which I really don't want to do.

So, I've done the next best thing and pushed 60fbee0 and updated the readme to be more descriptive and share the same description.

Thanks for the feedback.
