### ISSUE TITLE
Error installing requirements

### ISSUE THREAD

**Issue by MancV21** [d8ahazard/sd_dreambooth_extension#25]
Hi. Getting errors thrown when I run the WEBUI with the extension installed.

```
Error running install.py for extension sd_dreambooth_extension.
Command: "G:\StableDiffusion\stable-diffusion-webui\venv\Scripts\python.exe" "extensions\sd_dreambooth_extension\install.py"
Error code: 1
stdout: Installing requirements for Dreambooth
Installing torch and torchvision

stderr: Traceback (most recent call last):
  File "G:\StableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\install.py", line 12, in <module>
    run(f'"{python}" -m {torch_cmd}', "Installing torch and torchvision", "Couldn't install torch")
  File "G:\StableDiffusion\stable-diffusion-webui\launch.py", line 34, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install torch.
Command: "G:\StableDiffusion\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116
Error code: 2
stdout: Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116
Collecting torch==1.12.1+cu116
  Downloading https://download.pytorch.org/whl/cu116/torch-1.12.1%2Bcu116-cp310-cp310-win_amd64.whl (2388.4 MB)
     -----                                    0.3/2.4 GB 13.1 MB/s eta 0:02:37

```

Tried running as admin, no luck. Python is up to date as is AUTO's WebUI.

**Comment by Luke2642** [comment]
Had a similar issue. 

Copy contents of 
extensions\sd_dreambooth_extension\requirements.txt  
into the bottom of 
stable-diffusion-webui\requirements.txt

run webui again, and it works.

**Comment by Luke2642** [comment]
It didn't fully fix it for me either, starting training gave me 

AttributeError: 'UNet2DConditionModel' object has no attribute 'enable_gradient_checkpointing'

Which is supposedly fixed by just restarting, I guess after it installs requirements:

https://github.com/d8ahazard/sd_dreambooth_extension/issues/18

But it didn't. So, enable_gradient_checkpointing is in diffusers and I thought I'd try fix my cuda mismatch too, adding:

torchvision==0.14.0
diffusers==0.7.2
cudatoolkit==11.6

and that fixed it for me, now it's straining. So investigate your error, upgrade stuff and good luck :-)

**Comment by NaughtDZ** [comment]
> 

I have the same problem as you described. Thank you for your solution.

**Comment by NaughtDZ** [comment]
> Had a similar issue, except mine was
> 
> RuntimeError: Detected that PyTorch and torchvision were compiled with different CUDA versions. PyTorch has CUDA Version=11.6 and torchvision has CUDA Version=11.3. Please reinstall the torchvision that matches your PyTorch install. Press any key to continue . . .
> 
> I cut the contents of extensions\sd_dreambooth_extension\requirements.txt into the bottom of stable-diffusion-webui\requirements.txt
> 
> run webui again, and it works.

I have the same problem as you described. Thank you for your solution.

**Comment by dreamofmt** [comment]
Hello I am having a very similar issue as well, I was able to get past the Dreambooth tab not showing at all by adding the requirements_version accelerate and after doing various things like trying to upgrade the pip install cmd it recommends I am receiving the following and clicking the Train button does nothing at all, no messages or activity in the webui, just acts like a dead button and is probably because of this error message.

Error running install.py for extension sd_dreambooth_extension.
Command: "E:\AI\stable-diffusion-webui\venv\Scripts\python.exe" "extensions\sd_dreambooth_extension\install.py"
Error code: 1
stdout: Installing Requirements for Dreambooth

stderr: Traceback (most recent call last):
  File "E:\AI\stable-diffusion-webui\extensions\sd_dreambooth_extension\install.py", line 11, in <module>
    run(f'{python} -m pip install -r "{reqs}"', desc=f"Installing Requirements for {name}", errdesc=f"Couldn't install {name} requirements.")
  File "E:\AI\stable-diffusion-webui\launch.py", line 34, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install Dreambooth requirements..
Command: E:\AI\stable-diffusion-webui\venv\Scripts\python.exe -m pip install -r "E:\AI\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt"
Error code: 1

and then a lot of text which shows success and downloading files, and then right before it finishes it says this:

ERROR: Wheel 'opencv-python-headless' located at C:\Users\Nicole\AppData\Local\Temp\pip-unpack-wffhk96d\opencv_python_headless-4.6.0.66-cp36-abi3-win_amd64.whl is invalid.

If someone could please help me I would truly appreciate it as I don't have any idea how to proceed! Thank you for your time.

**Comment by Luke2642** [comment]
> 

I think the first error is you deleted requirements.txt, instead of cut the contents of requirements.txt from the extension folder and paste them to the end of webui folder requirements.txt.

The last error could be an old python version compatibility problem or something else. If you've broken something else just do a fresh git clone and start over with just one extension.

**Comment by MancV21** [comment]
> 

Na I didn't, I did it correctly. I fixed it by manually installing the requirements using `pip install -r requirements.txt`
