### ISSUE TITLE
Useless scheduler on model creation tab

### ISSUE THREAD

**Issue by knoopx** [d8ahazard/sd_dreambooth_extension#397]
The dropdown to select a scheduler on the model creation page is not used at all, there's no need to show it on the page.
As far as I understand, you are creating a `StableDiffusionPipeline` just for model conversion `pipe.save_pretrained()`, therefore any scheduler will do because you are not using the pipeline for sampling at all.

I had to check out the source code in order to understand what was the purpose of it.

![image](https://user-images.githubusercontent.com/100993/205402814-4f9273c1-badb-4be2-8747-32dc86ff0885.png)

**Comment by d8ahazard** [comment]
That's temporary. I had euler-a as the scheduler, but it was momentarily
broken for V2 models, which I'm working on implementing. Once done, this
will be relevant.

**Comment by d8ahazard** [comment]
So, V2 is up, and while it's largely irrelevant, it is still an optional setting in the original conversion script, so I'm leaving it in the UI, lest someone else gets mad because an obscure setting is not exposed.

Perhaps a compromise in the future would be an "advanced" checkbox, which, when toggled, shows/hides settings like this.
