### ISSUE TITLE
Running out of CUDA memory

### ISSUE THREAD

**Issue by Joedog6503** [d8ahazard/sd_dreambooth_extension#456]
Exception while training: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 12.00 GiB total capacity; 11.08 GiB already allocated; 0 bytes free; 11.25 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
 Allocated: 11.1GB
 Reserved: 11.2GB

I have a 3080 yet am running out of CUDA MEMORY, anyone know why this is happening?

**Comment by daaButcher** [comment]
heeeeeeeeeelp

**Comment by d8ahazard** [comment]
> Exception while training: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 12.00 GiB total capacity; 11.08 GiB already allocated; 0 bytes free; 11.25 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF Allocated: 11.1GB Reserved: 11.2GB
> 
> I have a 3080 yet am running out of CUDA MEMORY, anyone know why this is happening?

Nope, because you didn't use the issue template and/or specify the requested information, like the full error log showing the entire error, and/or your training settings.

Disable training the text encoder, ensure 8bit adam, xformers, and fp16 are used in "advanced". Please open an issue using the template if you require further assistance.
