### ISSUE TITLE
Can really the latest version work well?

### ISSUE THREAD

**Issue by ziyaxuanyi** [d8ahazard/sd_dreambooth_extension#463]
When I use the old version,it work well. But when I update the new version, it can't train.

it will print "please configure some concepts"

**Comment by ziyaxuanyi** [comment]
I think maybe thers are some parameters are not aligned

**Comment by ziyaxuanyi** [comment]
I think maybe thers are some parameters that are not aligned

**Comment by sepro** [comment]
This happened to me as well, clicking `save params` to force all params and concepts to be save resolved the issue.

**Comment by notchrisb** [comment]
@ziyaxuanyi  were you using VAE in your training?

**Comment by chakalakasp** [comment]
Heh, I say this understanding that the dev owes us nothing but, uh...

Dev: The check box says "don't cache latents" instead of "cache latents" because that's how it always was and if I changed it it'd be confusing

Also Dev: Hey, steps is now Epochs so hope you notice your model is now training for 2.7 million steps before you walk away from the computer

**Comment by d8ahazard** [comment]
Yes, it can. The readme has been updated with detailed instructions.

https://github.com/d8ahazard/sd_dreambooth_extension/blob/main/README.md
