### ISSUE TITLE
error when creating models

### ISSUE THREAD

**Issue by chickenzzx** [d8ahazard/sd_dreambooth_extension#568]
when i try to create a model i get an error but ive seen gpus with lower vram do it

 Restored system models.
 Allocated: 2.0GB
 Reserved: 2.0GB

 Allocated 2.0/2.0GB
 Reserved: 2.0/2.0GB
IndexError: tuple index out of range

Windows 10 Native

RTX 3080 10GB
![ss](https://user-images.githubusercontent.com/120831311/208266624-c784bdfd-579e-4e58-b2ec-9733ddd50ab3.png)

**Comment by simcop2387** [comment]
If this is what i've been experiencing, then the real problem is just above your screenshot:

```
stable-diffusion-stable-diffusion-api-1  | Exception while extracting model: module 'modules.sd_models' has no attribute 'get_closet_checkpoint_match'
```

Fixing the spelling on that call to be _closest_ fixes that error.  It's happening because the webui code updated and fixed the spelling of it, so when trying to extract the model from a .ckpt file it ends up erroring and isn't handled as well as it could be.  I've been meaning to make a PR on that to fix the issue and make it try both spellings before erroring

**Comment by d8ahazard** [comment]
This is probably an issue with the version of SD-WebUI you're using. But, I can't tell that, because you didn't bother filling out the form as requested. So, I'm not going to bother trying to sus out what your issue is without the proper information.

Update, submit a proper issue if you still need help.

Also, @simcop2387 - What? 

Yes, there's a typo, but if you look at the source for Auto1111, you'll see that the typo has *not* been fixed in the main branch.

![image](https://user-images.githubusercontent.com/1633844/208945247-fe61dd94-1659-4ecb-8f22-ffd77b14cb08.png)
