### ISSUE TITLE
Not working on Apple Silicon

### ISSUE THREAD

**Issue by lustfeind** [d8ahazard/sd_dreambooth_extension#60]
It says:
ModuleNotFoundError: No module named 'accelerate'

Edit:
I try this without success:

```
pip install accelerate deepspeed
accelerate config
```

**Comment by eddjrn** [comment]
try pip3 install accelerate

**Comment by le-wib** [comment]
Hello. I did every thing I could find in the comments, such as updating python, installing pip, pip install requirement, all of that load stuff and install things, but I'm still getting these errors when loading the envirement and the webui. Im not tech savy. If someone could have the amability to point me in the right direction

this is what I get : 

`
Reloading extensions
Reloading custom scripts
Error loading script: main.py
Traceback (most recent call last):
  File "/Users/jtaillez/Documents/stable-diffusion-webui/modules/scripts.py", line 170, in load_scripts
    exec(compiled, module.__dict__)
  File "/Users/jtaillez/Documents/stable-diffusion-webui/extensions/sd_dreambooth_extension-main/scripts/main.py", line 3, in <module>
    from dreambooth import conversion, dreambooth
  File "/Users/jtaillez/Documents/stable-diffusion-webui/extensions/sd_dreambooth_extension-main/dreambooth/conversion.py", line 26, in <module>
    from dreambooth.dreambooth import get_db_models
  File "/Users/jtaillez/Documents/stable-diffusion-webui/extensions/sd_dreambooth_extension-main/dreambooth/dreambooth.py", line 10, in <module>
    from dreambooth.train_dreambooth import main
  File "/Users/jtaillez/Documents/stable-diffusion-webui/extensions/sd_dreambooth_extension-main/dreambooth/train_dreambooth.py", line 20, in <module>
    from accelerate import Accelerator
ModuleNotFoundError: No module named 'accelerate'

Reloading modules: modules.ui
Refreshing Model List
Restarting Gradio

Thanks for being a Gradio user! If you have questions or feedback, please join our Discord server and chat with us: https://discord.gg/feTf9x3ZSB
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
`

**Comment by le-wib** [comment]
How do you do that ?, because I launch SB using this in the mac Terminal : run_webui_mac.sh

**Comment by ppietro21** [comment]
Same problem here, I think the problem is python not found the folder.
I use: pip3 install accelerate
and it installed without problem, if I try to install it again it say:

Requirement already satisfied: accelerate in /opt/homebrew/lib/python3.10/site-packages (0.14.0)
Requirement already satisfied: pyyaml in /opt/homebrew/lib/python3.10/site-packages (from accelerate) (6.0)
Requirement already satisfied: numpy>=1.17 in /opt/homebrew/lib/python3.10/site-packages (from accelerate) (1.23.4)
Requirement already satisfied: torch>=1.4.0 in /opt/homebrew/lib/python3.10/site-packages (from accelerate) (1.13.0)
Requirement already satisfied: packaging>=20.0 in /opt/homebrew/lib/python3.10/site-packages (from accelerate) (21.3)
Requirement already satisfied: psutil in /opt/homebrew/lib/python3.10/site-packages (from accelerate) (5.9.4)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /opt/homebrew/lib/python3.10/site-packages (from packaging>=20.0->accelerate) (3.0.9)
Requirement already satisfied: typing-extensions in /opt/homebrew/lib/python3.10/site-packages (from torch>=1.4.0->accelerate) (4.4.0)

So all is installed, but when I run SD the ModuleNotFoundError: No module named 'accelerate' appears.
I'm not using environments just the normal installation.

Thanks for the help.
Pablo.

**Comment by d8ahazard** [comment]
So I *think* I maybe fixed this?

I suspect the problem is that when I try to install the dreambooth extension, I was looking for an absolute path to the requirements.txt file. Instead, I just made it use the path relative to the script, which does the same thing, at least in my tests.

Please do an update, restart the WebUI entirely, and let me know if you get the same error.

**Comment by lustfeind** [comment]
@d8ahazard : Thank you for your update, I think we get closer. Now I got this error:

```
Error loading script: main.py
Traceback (most recent call last):
  File "/Users/myuser/Documents/stable-diffusion-webui/modules/scripts.py", line 170, in load_scripts
    exec(compiled, module.__dict__)
  File "/Users/myuser/Documents/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/main.py", line 3, in <module>
    from dreambooth import conversion, dreambooth
  File "/Users/myuser/Documents/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/conversion.py", line 26, in <module>
    from dreambooth.dreambooth import get_db_models
  File "/Users/myuser/Documents/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dreambooth.py", line 10, in <module>
    from dreambooth.train_dreambooth import main
  File "/Users/myuser/Documents/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 23, in <module>
    from diffusers import AutoencoderKL, DDIMScheduler, DDPMScheduler, StableDiffusionPipeline, UNet2DConditionModel
ModuleNotFoundError: No module named 'diffusers'
```

**Comment by lustfeind** [comment]
@d8ahazard : Not sure,.. so I'm posting here the full output:

```
myuser@MacBook-Pro-von-myuser stable-diffusion-webui % ./run_webui_mac.sh       
To make your changes take effect please reactivate your environment
WARNING: overwriting environment variables set in the machine
overwriting variable PYTORCH_ENABLE_MPS_FALLBACK
Already up to date.
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
Error setting up CodeFormer:
Traceback (most recent call last):
  File "/Users/myuser/Documents/stable-diffusion-webui/modules/codeformer_model.py", line 38, in setup_model
    from facelib.utils.face_restoration_helper import FaceRestoreHelper
  File "/Users/myuser/Documents/stable-diffusion-webui/repositories/CodeFormer/facelib/utils/face_restoration_helper.py", line 7, in <module>
    from facelib.detection import init_detection_model
  File "/Users/myuser/Documents/stable-diffusion-webui/repositories/CodeFormer/facelib/detection/__init__.py", line 11, in <module>
    from .yolov5face.face_detector import YoloDetector
  File "/Users/myuser/Documents/stable-diffusion-webui/repositories/CodeFormer/facelib/detection/yolov5face/face_detector.py", line 20, in <module>
    IS_HIGH_VERSION = tuple(map(int, torch.__version__.split('+')[0].split('.'))) >= (1, 9, 0)
ValueError: invalid literal for int() with base 10: 'dev20220922'

Error loading script: main.py
Traceback (most recent call last):
  File "/Users/myuser/Documents/stable-diffusion-webui/modules/scripts.py", line 170, in load_scripts
    exec(compiled, module.__dict__)
  File "/Users/myuser/Documents/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/main.py", line 3, in <module>
    from dreambooth import conversion, dreambooth
  File "/Users/myuser/Documents/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/conversion.py", line 26, in <module>
    from dreambooth.dreambooth import get_db_models
  File "/Users/myuser/Documents/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dreambooth.py", line 10, in <module>
    from dreambooth.train_dreambooth import main
  File "/Users/myuser/Documents/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 23, in <module>
    from diffusers import AutoencoderKL, DDIMScheduler, DDPMScheduler, StableDiffusionPipeline, UNet2DConditionModel
ModuleNotFoundError: No module named 'diffusers'

LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Loading weights [5b2f6d66] from /Users/myuser/Documents/stable-diffusion-webui/models/Stable-diffusion/sd-v1-4.ckpt
Applying cross attention optimization (InvokeAI).
Model loaded.
Loaded a total of 0 textual inversion embeddings.
Embeddings: 
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
```

**Comment by SAC020** [comment]
Installed for the first time after this message, I have the same error (no module called accelerate), on Windows. Checked for extension updates in Stable Diffusion and it reports all up to date

**Comment by d8ahazard** [comment]
> Installed for the first time after this message, I have the same error (no module called accelerate), on Windows. Checked for extension updates in Stable Diffusion and it reports all up to date

Give it another go, I got a bit dumb last night and over-corrected. I think we should be good both on windows and OSX now.

**Comment by lustfeind** [comment]
@d8ahazard ok, thank you. My installation seems fault, still getting ModuleNotFoundError: No module named 'diffusers'.
At the moment I don't know how to fix that.

**Comment by SAC020** [comment]
> > Installed for the first time after this message, I have the same error (no module called accelerate), on Windows. Checked for extension updates in Stable Diffusion and it reports all up to date
> 
> Give it another go, I got a bit dumb last night and over-corrected. I think we should be good both on windows and OSX now.

Now I cannot start webui at all, it crashes with:

```
RuntimeError: Detected that PyTorch and torchvision were compiled with different CUDA versions. PyTorch has CUDA Version=11.6 and torchvision has CUDA Version=11.3. Please reinstall the torchvision that matches your PyTorch install.
Press any key to continue . . .
```

**Comment by SAC020** [comment]
> https://download.pytorch.org

I've ran it again and now it works. Probably some repos who got updated in the meantime.

TY

**Comment by lustfeind** [comment]
Any Apple Silicon user can confirm that this is running on your machine? After a clean install of SD I'm running out of options.

**Comment by Igrekess** [comment]
Yes I can confirm it seems to works on my mbp, M1 max 32. I have no error message at start, and I'm able to run a training with Dreambooth (but it's quite slow, I did'nt try yet to complete a training)

But it has been a difficult journey to get it work.
Bassicly I tried to fix all the problems one by one and at one point it start to work ^^'

I'm sorry I can't help much because I did so many tries to fix the issues that I'm not sure of what solve everything at the end, and I'm not very into "the code".

Here is some steps that seems to me important :

- first don't do like me at the beginning : use a virtual environment, do a fresh clean install of automatic 1111... 
 
- at one point I updated my pytorch to the last nightly build :
```
conda install \
  pytorch \
  torchvision \
  -c pytorch-nightly \
  -n web-ui
```

- I had to do manually install "accelerate' in the conda env web-ui
`pip install accelerate` 
- I had to uninstall tokenizers, transformers and reinstall it into my conda env web-ui :
```
conda uninstall tokenizers, transformers
pip install transformers
```

**Comment by d8ahazard** [comment]
> Any Apple Silicon user can confirm that this is running on your machine? After a clean install of SD I'm running out of options.
> 
> Still getting: ModuleNotFoundError: No module named 'diffusers'
> 
> But I already installed the diffusers with pip3 install diffusers

Hey there, are you still having troubles?

Could you try running this script instead of the webui-user.sh file?

https://github.com/d8ahazard/sd_dreambooth_extension/blob/main/webui-user-dreambooth.sh

**Comment by d8ahazard** [comment]
> @d8ahazard Thank you, but the script don't works:
> 
> ```
> Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116
> ERROR: Could not find a version that satisfies the requirement torch==1.12.1+cu116 (from versions: 1.11.0, 1.12.0, 1.12.1, 1.13.0)
> ERROR: No matching distribution found for torch==1.12.1+cu116
> ```
> 
> Now when I press the Train Button nothing happens: #142

You know, I just had the dumbest realization.

You're probably getting this error (just a guess) because there isn't that specific torch/cuda version available for OSX.

But, of course, we really don't need that specific version for anything but windows, so I'll remove that bit from the installer.

You may need to blow away your venv and start from scratch, but I suspect you should really be good to go now.

**Comment by lustfeind** [comment]
@d8ahazard : It's working now! Thank you, I appreciate your great work a lot! Thumbs up!

**Comment by d8ahazard** [comment]
Awesome!
