### ISSUE TITLE
Suggestion - Use branches?

### ISSUE THREAD

**Issue by entmike** [d8ahazard/sd_dreambooth_extension#69]
For @d8ahazard - Have you considered having a traditional `main` branch for end-users and a `development` branch for active development?  I know this is a relatively new project that's gaining some visibility, however with the bug wack-a-mole going on, it might help curb some of these new/repeated Issues being reported?  As a developer myself, if I knew enough about ML training, I'd volunteer to help squash some bugs, but currently the best I can offer is reporting Issues or debugging breaking changes, but perhaps a branch would help.

Anyways, every developer works differently, so if this isn't your style, I get it!  Just thinking it may help with the volume of Issues bubbling up in last 2 days and going forward.

Keep up the good work!

**Comment by d8ahazard** [comment]
> For @d8ahazard - Have you considered having a traditional `main` branch for end-users and a `development` branch for active development? I know this is a relatively new project that's gaining some visibility, however with the bug wack-a-mole going on, it might help curb some of these new/repeated Issues being reported? As a developer myself, if I knew enough about ML training, I'd volunteer to help squash some bugs, but currently the best I can offer is reporting Issues or debugging breaking changes, but perhaps a branch would help.
> 
> Anyways, every developer works differently, so if this isn't your style, I get it! Just thinking it may help with the volume of Issues bubbling up in last 2 days and going forward.
> 
> Keep up the good work!

LOL, I have. As you said, right now, I'm just playing whack-a-mole to try and achieve a stable(ish) state. 

I think that with the most recent commits I've dropped, I should almost be at that point, and then I will most likely do just that, although then having separate branches breaks issues with people being able to use it from the UI, unless a branch selection is added.

Either way, the goal is still to get it so that it isn't broken because of dumb stuff I did in re-re-re-re porting the training script. Once that's there, then I'll start doing subsequent features/fixes to their own branches.
