### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ameeratgithub** [d8ahazard/sd_dreambooth_extension#830]
I've updated my dreambooth extension recently. I am receiving an error when I try to create a new model. 

How can I solve this?

![image](https://user-images.githubusercontent.com/55062550/214054353-8225a77b-ced0-48eb-833f-91934817ddc5.png)

### Steps to reproduce
1. Run webui-user.bat to open SD Web UI
2. Go to extensions
3. Click on Check for Updates button
4. Click on Apply and Restart if you don't have latest version of dreambooth extension
5. Go to Dreambooth tab
6. Click on create
7. Try to create a model

**Comment by bosbrand** [comment]
Same here...

**Comment by bosbrand** [comment]
@mykeehu Nope, google chrome

**Comment by bosbrand** [comment]
OMG... ctrl F5 solved it.

**Comment by d8ahazard** [comment]
Yeah, pretty sure we went over this yesterday...

Ctrl+F5 does this crazy thing where it forces the webpage to reload from server. In the case of auto1111, this is necessary because the magic "restart and refresh" button doesn't actually restart and refresh everything - doubly so for the backend components like "sd_to_diff".

So, if I add a new UI element, and someone updates using the Auto1111 UI, and the web page doesn't get entirely refreshed, then the number of config values being sent to the server doesn't match up with the number required, and then we get a list index out of range error.

**Comment by mykeehu** [comment]
@d8ahazard these last two paragraphs could go in FAQ for such a mistake ;)

**Comment by d8ahazard** [comment]
> @d8ahazard these last two paragraphs could go in FAQ for such a mistake ;)

I feel like the FAQ would be a thousand pages long if we documented every stupid thing that happens as a result of things not working/loading/installing right.
