### ISSUE TITLE
Multiple concepts training bleeds into one another

### ISSUE THREAD

**Issue by Claxiz** [d8ahazard/sd_dreambooth_extension#873]
`
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: fd4461d44c7256d56889f5b5ed9fb660a859172f
Installing requirements for Web UI
Skipping dreambooth installation.
Dreambooth revision is 9f4d931a319056c537d24669cb950d146d1537b0
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] torch version 1.12.1+cu116 installed.
[+] torchvision version 0.13.1+cu116 installed.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
yes
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
yes
**Have you updated Dreambooth to the latest revision?**
yes
**Have you updated the Stable-Diffusion-WebUI to the latest version?**
yes
**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**
ok
**Describe the bug**

When training more than a single concept, there is a good chance that the concepts attributes bleed into one another, appearing when prompting the concepts. For example, concept 1 holds a polearm, but concept 2 holds a dagger, when prompting concept 1, they sometimes are holding concept's 2 dagger. Another example is small parts of swapped clothing between the subjects. Another example is eye color being shared between the concepts. 

This concept bleed effect seemingly occurs more often the more overfit the trained model is. I have tried multiple recent commits, nothing seems to fix this problem, and I have made tons of test models to see if I am just going insane or not, but I've asked other users of this extension and they are identifying the same issue. Additionally, this concept bleed effect occurs regardless if you caption your dataset, or you do not caption it.

Unrelated to the bug, but it's a total pain in the ass to train multiple concepts with this extension, nothing seems to work unless you put the concepts in one folder.

Please fix!

**Environment**

What OS?
Windows 10
What GPU are you using?
GTX 3090
**Screenshots/Config**
Examples -
Instance of concept subject 1 holding a weapon that belongs to concept subject 2, captioned for subject 2 as 'polearm'
![00522-2476169051-osvelvet,](https://user-images.githubusercontent.com/121401900/215048116-9a30ec4a-43b4-453f-964b-65f488873761.png)

Wrong eye color swap
![00358-2398320959-osgwen,](https://user-images.githubusercontent.com/121401900/215047480-732797a9-d9bc-4954-b18b-0f373e023c84.png)
![00586-2476169051-osvelvet,](https://user-images.githubusercontent.com/121401900/215047989-9d7f489e-4afb-47b1-b0fa-d7321f932f6a.png)

**Comment by cerega66** [comment]
DB trains on an average basis. At a certain point, it became possible to use several concepts at the same time, but in reality this is not the case. For the trainer, you are still training one concept only now the training data is slightly different set of tokens, but still has a lot in common, leading to implicit mixing of your concepts. Right now there is no method of training on DB that will give you 100% non-mixing of concepts.

**Comment by MrMondragon** [comment]
same issue here, and this is new: I have an older model where I was able to train 13 concepts, members of a comics cast.

Now, when I do the same, using the same config, all prompts come out with the first character.

When I saw this, I went on and tried another model, with only two, unrelated subjects (a character and a style) and it only trained the first concept, ignoring the second almost entirely

**Comment by d8ahazard** [comment]
I feel like this is less of an issue than just how Dreambooth works. Batching is already set up so that each concept is trained separately from one another, so even if training a batch of 10 images at a time, that batch will only ever consist of your subject.

As was already pointed out, Stable Diffusion isn't necessarily designed for specificity, but generalization. So, show it a bunch of images of several characters, and it'll do it's best to learn what that image is, but it's also going to learn about the various features of that image itself.

One suggestion is adjusting the ratio of text encoder training - less text encoder might help somewhat. Another is maybe more prompt specificity. If you don't want one character holding a dagger, put dagger as a negative prompt. 

But, as this isn't necessarily a bug, but more a limitation of this type of model, I'm going to close the issue. Feel free to hop on the Discord if you want to pick the brains of some of our other more seasoned trainers.
