### ISSUE TITLE
Last update broke Automatic1111

### ISSUE THREAD

**Issue by econundrum** [d8ahazard/sd_dreambooth_extension#983]
The last update to Dream booth broke my Automatic1111 environment I had to delete the venv folder and get it to setup everything again. appears to stop pytorch accessing Cuda notice there where changes to the requirements.txt for Dreambooth

**Comment by ArrowM** [comment]
Thanks for deleting the whole template and not posting any console output whatsoever. good stuff

**Comment by d8ahazard** [comment]
And frankly, we don't have the time to deal with every person who posts a
one-sentence issue when we're specifically asking for details that will
help us troubleshoot issues.

I could personally care less if you find that to be fair or not.
Sorry...not sorry?

**Comment by econundrum** [comment]
That's fine I won't bother you again. Goodluck with everything.

**Comment by Ark-kun** [comment]
@d8ahazard Every mistake you make is an opportunity to learn.

**Comment by ChunkyPanda03** [comment]
@Ark-kun I mean we should have filled it out and included the log but the issue is that he immediately closed it. In the mean time I figured out the issue it was that I was using an older version of automatic1111 which resulted in dependency conflicts.

**Comment by ChunkyPanda03** [comment]
@Ark-kun I mean we should have filled it out and included the log but the issue is that he immediately closed it without giving us a chance to submit it. In the mean time I figured out the issue it was that I was using an older version of automatic1111 which resulted in dependency conflicts.

**Comment by d8ahazard** [comment]
> @Ark-kun I mean we should have filled it out and included the log but the issue is that he immediately closed it. In the mean time I figured out the issue it was that I was using an older version of automatic1111 which resulted in dependency conflicts.

Crazy part is - the form that was never filled out explicitly asks if you're on the latest version of Auto1111.

Also, nothing is stopping anybody from filling out the issue properly and re-opening or re-submitting.

**Comment by ChunkyPanda03** [comment]
Dear @d8ahazard

What can I say I'm human I make mistakes all the time, I for one am not ashamed of it. sometimes we just need a little push in the right direction. I was merely responding to a peer because an interesting piece of software I wish to try out was unfortunately not working upon installation. It in fact destroyed the entire virtual environments I was running, leading to a few hours of debugging. However it was time not wasted because I figured out the problem and I've learned from it and have been moving on since. However here you are still complaining. If it is the logs you're looking for I can reproduce the issue and send it again in hopes that it will have something you can gain from it.

Sincerely, ChunkyPanda03

**Comment by d8ahazard** [comment]
> Dear @d8ahazard
> 
> What can I say I'm human I make mistakes all the time, I for one am not ashamed of it. sometimes we just need a little push in the right direction. I was merely responding to a peer because an interesting piece of software I wish to try out was unfortunately not working upon installation. It in fact destroyed the entire virtual environments I was running, leading to a few hours of debugging. However it was time not wasted because I figured out the problem and I've learned from it and have been moving on since. However here you are still complaining. If it is the logs you're looking for I can reproduce the issue and send it again in hopes that it will have something you can gain from it.
> 
> Sincerely, ChunkyPanda03

This is fun.

I was simply replying to your previous statement here:

"but the issue is that he immediately closed it"

As well as your observation that the issue was a result of using an older version of Auto1111.

To wit - I was pointing out that the issues can be re-opened at any time; as well as the fact that the purpose of the form is to ask questions that make people examine their environment for a second, which very well would have helped us both avoid this entire interaction.
